### ISSUE TITLE
We shouldn't highlight objects that are hidden

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#837]
When we click on the tree, regardless of whether the object is hidden or not, it will still be selected.

Hidden objects should be filtered out of the selection to reflect the current presentation of the model

To do this properly, we probably need to do #813 first

**Comment by JamesMilnerUK** [comment]
Let's revisit this after groups (#803) has merged as we change some of the Tree code in there.

**Comment by JamesMilnerUK** [comment]
I think this is fixed now in staging? @carmenfan @Charence

**Comment by carmenfan** [comment]
this still happens if you're highlighting a parent. See here:
![b1](https://user-images.githubusercontent.com/11945337/39310315-fcce9f6e-4961-11e8-80cd-7fae6d1261c0.gif)

#813 might have fixed this already though.

**Comment by carmenfan** [comment]
this is fixed in #813
